const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.join(__dirname, '../database.db');
const db = new sqlite3.Database(dbPath);

const sampleCars = [
  {
    user_id: 1,
    brand: 'BMW',
    model: '3 Series 320d',
    year: 2020,
    price: 35900,
    body_type: 'Sedan',
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    mileage: 45000,
    engine_size: 1995,
    power_hp: 190,
    doors: 4,
    seats: 5,
    color: 'Black',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    navigation_system: 1,
    parking_sensors: 1,
    leather_seats: 1,
    country: 'Germany',
    city: 'Munich',
    description: 'Well-maintained BMW 3 Series with full service history',
    images: JSON.stringify(['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800'])
  },
  {
    user_id: 1,
    brand: 'Audi',
    model: 'A4 2.0 TDI',
    year: 2019,
    price: 28500,
    body_type: 'Sedan',
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    mileage: 62000,
    engine_size: 1968,
    power_hp: 150,
    doors: 4,
    seats: 5,
    color: 'Silver',
    condition: 'Used',
    previous_owners: 2,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    navigation_system: 1,
    country: 'Germany',
    city: 'Berlin',
    description: 'Reliable Audi A4 in excellent condition',
    images: JSON.stringify(['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800'])
  },
  {
    user_id: 1,
    brand: 'Mercedes-Benz',
    model: 'C 200',
    year: 2021,
    price: 42900,
    body_type: 'Sedan',
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    mileage: 28000,
    engine_size: 1496,
    power_hp: 184,
    doors: 4,
    seats: 5,
    color: 'White',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    cruise_control: 1,
    navigation_system: 1,
    parking_camera: 1,
    leather_seats: 1,
    country: 'Germany',
    city: 'Stuttgart',
    description: 'Luxurious Mercedes C-Class with premium features',
    images: JSON.stringify(['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'])
  },
  {
    user_id: 1,
    brand: 'Volkswagen',
    model: 'Golf 1.5 TSI',
    year: 2020,
    price: 22900,
    body_type: 'Hatchback',
    fuel_type: 'Petrol',
    transmission: 'Manual',
    mileage: 38000,
    engine_size: 1498,
    power_hp: 130,
    doors: 5,
    seats: 5,
    color: 'Blue',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    country: 'Germany',
    city: 'Wolfsburg',
    description: 'Popular VW Golf with low mileage',
    images: JSON.stringify(['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800'])
  },
  {
    user_id: 1,
    brand: 'Tesla',
    model: 'Model 3 Long Range',
    year: 2022,
    price: 48900,
    body_type: 'Sedan',
    fuel_type: 'Electric',
    transmission: 'Automatic',
    mileage: 15000,
    power_hp: 350,
    doors: 4,
    seats: 5,
    color: 'Red',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    cruise_control: 1,
    navigation_system: 1,
    parking_camera: 1,
    battery_capacity: 75,
    electric_range: 580,
    country: 'Netherlands',
    city: 'Amsterdam',
    description: 'Tesla Model 3 with Autopilot and premium interior',
    images: JSON.stringify(['https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800'])
  },
  {
    user_id: 1,
    brand: 'Ford',
    model: 'Focus ST',
    year: 2018,
    price: 19900,
    body_type: 'Hatchback',
    fuel_type: 'Petrol',
    transmission: 'Manual',
    mileage: 72000,
    engine_size: 1999,
    power_hp: 250,
    doors: 5,
    seats: 5,
    color: 'Orange',
    condition: 'Used',
    previous_owners: 2,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    country: 'UK',
    city: 'London',
    description: 'Sporty Ford Focus ST in great condition',
    images: JSON.stringify(['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800'])
  },
  {
    user_id: 1,
    brand: 'Toyota',
    model: 'Corolla Hybrid',
    year: 2021,
    price: 24900,
    body_type: 'Sedan',
    fuel_type: 'Hybrid',
    transmission: 'Automatic',
    mileage: 32000,
    engine_size: 1798,
    power_hp: 122,
    doors: 4,
    seats: 5,
    color: 'Gray',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    cruise_control: 1,
    parking_sensors: 1,
    country: 'Belgium',
    city: 'Brussels',
    description: 'Fuel-efficient Toyota Corolla Hybrid',
    images: JSON.stringify(['https://images.unsplash.com/photo-1623869675781-80aa31e446c5?w=800'])
  },
  {
    user_id: 1,
    brand: 'Mazda',
    model: 'MX-5 RF',
    year: 2020,
    price: 29900,
    body_type: 'Convertible',
    fuel_type: 'Petrol',
    transmission: 'Manual',
    mileage: 18000,
    engine_size: 1998,
    power_hp: 184,
    doors: 2,
    seats: 2,
    color: 'Red',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    leather_seats: 1,
    country: 'France',
    city: 'Paris',
    description: 'Fun-to-drive Mazda MX-5 with retractable hardtop',
    images: JSON.stringify(['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800'])
  },
  {
    user_id: 1,
    brand: 'Volvo',
    model: 'XC60 T6',
    year: 2019,
    price: 38900,
    body_type: 'SUV',
    fuel_type: 'Plug-in Hybrid',
    transmission: 'Automatic',
    mileage: 48000,
    engine_size: 1969,
    power_hp: 340,
    doors: 5,
    seats: 5,
    color: 'Black',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    cruise_control: 1,
    navigation_system: 1,
    parking_camera: 1,
    leather_seats: 1,
    heated_seats: 1,
    sunroof: 1,
    battery_capacity: 11,
    electric_range: 45,
    country: 'Sweden',
    city: 'Stockholm',
    description: 'Premium Volvo XC60 hybrid with advanced safety features',
    images: JSON.stringify(['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800'])
  },
  {
    user_id: 1,
    brand: 'Hyundai',
    model: 'Kona Electric',
    year: 2021,
    price: 32900,
    body_type: 'SUV',
    fuel_type: 'Electric',
    transmission: 'Automatic',
    mileage: 22000,
    power_hp: 204,
    doors: 5,
    seats: 5,
    color: 'Blue',
    condition: 'Used',
    previous_owners: 1,
    accident_free: 1,
    service_history: 1,
    air_conditioning: 1,
    cruise_control: 1,
    navigation_system: 1,
    parking_sensors: 1,
    battery_capacity: 64,
    electric_range: 484,
    country: 'Spain',
    city: 'Madrid',
    description: 'Practical electric SUV with excellent range',
    images: JSON.stringify(['https://images.unsplash.com/photo-1617654112368-307921291f42?w=800'])
  }
];

console.log('🚗 Inserting sample cars...');

const insertStmt = db.prepare(`
  INSERT INTO cars (
    user_id, brand, model, year, price, body_type, fuel_type, transmission,
    mileage, engine_size, power_hp, doors, seats, color, condition,
    previous_owners, accident_free, service_history, air_conditioning,
    cruise_control, navigation_system, parking_sensors, parking_camera,
    leather_seats, heated_seats, sunroof, battery_capacity, electric_range,
    country, city, description, images
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

sampleCars.forEach((car, index) => {
  insertStmt.run([
    car.user_id, car.brand, car.model, car.year, car.price, car.body_type,
    car.fuel_type, car.transmission, car.mileage, car.engine_size, car.power_hp,
    car.doors, car.seats, car.color, car.condition, car.previous_owners,
    car.accident_free, car.service_history, car.air_conditioning, car.cruise_control,
    car.navigation_system, car.parking_sensors, car.parking_camera, car.leather_seats,
    car.heated_seats, car.sunroof, car.battery_capacity, car.electric_range,
    car.country, car.city, car.description, car.images
  ], (err) => {
    if (err) {
      console.error(`❌ Error inserting car ${index + 1}:`, err.message);
    } else {
      console.log(`✅ Inserted: ${car.brand} ${car.model}`);
    }
  });
});

insertStmt.finalize(() => {
  console.log('🎉 Sample car data inserted successfully!');
  db.close();
});
