const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const db = new sqlite3.Database(path.join(__dirname, '../database.db'));

const ebikes = [
  {
    user_id: 1,
    brand: 'Specialized',
    model: 'Turbo Levo Expert',
    year: 2023,
    price: 8500,
    type: 'Mountain',
    motor_type: 'Mid-drive',
    motor_power: 565,
    battery_capacity: 700,
    range_min: 80,
    range_max: 120,
    frame_material: 'Carbon',
    suspension: 'Full',
    brakes: 'Hydraulic Disc',
    gear_system: 'SRAM GX Eagle 12-speed',
    tire_size: '29"',
    weight: 22.5,
    condition: 'Used',
    mileage: 850,
    city: 'Munich',
    description: 'Premium e-MTB with carbon frame and top components',
    images: '/images/ebikes/specialized-levo.jpg',
    gears: 12
  },
  {
    user_id: 2,
    brand: 'Trek',
    model: 'Powerfly FS 9',
    year: 2024,
    price: 6200,
    type: 'Mountain',
    motor_type: 'Mid-drive',
    motor_power: 625,
    battery_capacity: 625,
    range_min: 70,
    range_max: 100,
    frame_material: 'Aluminum',
    suspension: 'Full',
    brakes: 'Shimano Hydraulic',
    gear_system: 'Shimano Deore 12-speed',
    tire_size: '27.5"',
    weight: 24,
    condition: 'New',
    city: 'Berlin',
    description: 'Trail-ready e-MTB with Bosch motor',
    images: '/images/ebikes/trek-powerfly.jpg',
    gears: 12
  },
  {
    user_id: 1,
    brand: 'Riese & Müller',
    model: 'Charger3 GT Vario',
    year: 2023,
    price: 5800,
    type: 'Trekking',
    motor_type: 'Mid-drive',
    motor_power: 625,
    battery_capacity: 625,
    range_min: 100,
    range_max: 140,
    frame_material: 'Aluminum',
    suspension: 'Front',
    brakes: 'Hydraulic Disc',
    gear_system: 'Enviolo Stepless',
    tire_size: '28"',
    weight: 27,
    condition: 'Used',
    mileage: 2400,
    city: 'Hamburg',
    description: 'Premium trekking e-bike with automatic transmission',
    images: '/images/ebikes/rm-charger.jpg'
  },
  {
    user_id: 3,
    brand: 'Cube',
    model: 'Touring Hybrid Pro 625',
    year: 2024,
    price: 3200,
    type: 'Trekking',
    motor_type: 'Mid-drive',
    motor_power: 500,
    battery_capacity: 625,
    range_min: 90,
    range_max: 130,
    frame_material: 'Aluminum',
    suspension: 'Front',
    brakes: 'Hydraulic Disc',
    gear_system: 'Shimano Deore 10-speed',
    tire_size: '28"',
    weight: 25.5,
    condition: 'New',
    city: 'Frankfurt',
    description: 'Comfortable touring bike for long distances',
    images: '/images/ebikes/cube-touring.jpg',
    gears: 10
  },
  {
    user_id: 2,
    brand: 'Gazelle',
    model: 'Ultimate C380+ HMB',
    year: 2023,
    price: 4100,
    type: 'City',
    motor_type: 'Mid-drive',
    motor_power: 500,
    battery_capacity: 500,
    range_min: 80,
    range_max: 110,
    frame_material: 'Aluminum',
    suspension: 'Front',
    brakes: 'Hydraulic Disc',
    gear_system: 'Enviolo Stepless',
    tire_size: '28"',
    weight: 26,
    condition: 'Used',
    mileage: 1200,
    city: 'Cologne',
    description: 'Elegant city e-bike with belt drive',
    images: '/images/ebikes/gazelle-ultimate.jpg'
  },
  {
    user_id: 1,
    brand: 'Kalkhoff',
    model: 'Image 5.B Move',
    year: 2024,
    price: 2900,
    type: 'City',
    motor_type: 'Mid-drive',
    motor_power: 500,
    battery_capacity: 500,
    range_min: 70,
    range_max: 100,
    frame_material: 'Aluminum',
    brakes: 'Hydraulic Disc',
    gear_system: 'Shimano Nexus 8-speed',
    tire_size: '28"',
    weight: 24.5,
    condition: 'New',
    city: 'Stuttgart',
    description: 'Comfortable city bike for daily commuting',
    images: '/images/ebikes/kalkhoff-image.jpg',
    gears: 8
  },
  {
    user_id: 3,
    brand: 'Haibike',
    model: 'Sduro FullSeven 7.0',
    year: 2023,
    price: 3500,
    type: 'Mountain',
    motor_type: 'Mid-drive',
    motor_power: 500,
    battery_capacity: 500,
    range_min: 60,
    range_max: 90,
    frame_material: 'Aluminum',
    suspension: 'Full',
    brakes: 'Hydraulic Disc',
    gear_system: 'Shimano SLX 11-speed',
    tire_size: '27.5"',
    weight: 23,
    condition: 'Used',
    mileage: 1800,
    city: 'Dresden',
    description: 'Reliable e-MTB with Yamaha drive',
    images: '/images/ebikes/haibike-sduro.jpg',
    gears: 11
  },
  {
    user_id: 2,
    brand: 'Urban Arrow',
    model: 'Family Active Plus',
    year: 2024,
    price: 5600,
    type: 'Cargo',
    motor_type: 'Mid-drive',
    motor_power: 625,
    battery_capacity: 500,
    range_min: 50,
    range_max: 80,
    frame_material: 'Aluminum',
    brakes: 'Hydraulic Disc',
    gear_system: 'Enviolo Stepless',
    tire_size: '20"',
    weight: 60,
    condition: 'New',
    city: 'Amsterdam',
    description: 'Premium cargo bike for family transport',
    images: '/images/ebikes/urban-arrow.jpg'
  },
  {
    user_id: 1,
    brand: 'Bulls',
    model: 'Iconic Evo TR 1',
    year: 2023,
    price: 2400,
    type: 'Trekking',
    motor_type: 'Mid-drive',
    motor_power: 500,
    battery_capacity: 500,
    range_min: 75,
    range_max: 105,
    frame_material: 'Aluminum',
    suspension: 'Front',
    brakes: 'Hydraulic Disc',
    gear_system: 'Shimano Deore 10-speed',
    tire_size: '28"',
    weight: 25,
    condition: 'Used',
    mileage: 3200,
    city: 'Dortmund',
    description: 'Solid trekking bike at affordable price',
    images: '/images/ebikes/bulls-iconic.jpg',
    gears: 10
  },
  {
    user_id: 3,
    brand: 'Stromer',
    model: 'ST5 ABS',
    year: 2024,
    price: 9800,
    type: 'City',
    motor_type: 'Hub motor',
    motor_power: 850,
    battery_capacity: 983,
    range_min: 120,
    range_max: 180,
    frame_material: 'Carbon',
    brakes: 'ABS Hydraulic',
    gear_system: 'Pinion C1.12',
    tire_size: '27"',
    weight: 28,
    max_speed: 45,
    condition: 'New',
    city: 'Zurich',
    description: 'Top-of-the-line speed pedelec with ABS',
    images: '/images/ebikes/stromer-st5.jpg',
    gears: 12
  }
];

const caravans = [
  {
    user_id: 1,
    brand: 'Hymer',
    model: 'B-Klasse ModernComfort I 600',
    year: 2022,
    price: 89500,
    type: 'Motorhome',
    subtype: 'Integrated',
    length: 6.36,
    width: 2.32,
    height: 2.98,
    weight_empty: 3200,
    weight_total: 3500,
    sleeping_capacity: 4,
    num_beds: 2,
    num_axles: 2,
    mileage: 15000,
    fuel_type: 'Diesel',
    engine_size: 2.3,
    power_hp: 140,
    transmission: 'Manual',
    condition: 'Used',
    city: 'Stuttgart',
    description: 'Premium integrated motorhome with modern interior',
    images: '/images/caravans/hymer-b-class.jpg',
    heating: 1,
    ac: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 2,
    brand: 'Dethleffs',
    model: 'Globebus I 1',
    year: 2023,
    price: 67900,
    type: 'Motorhome',
    subtype: 'Semi-Integrated',
    length: 5.99,
    width: 2.32,
    height: 2.89,
    weight_empty: 2950,
    weight_total: 3500,
    sleeping_capacity: 3,
    num_beds: 2,
    num_axles: 2,
    mileage: 8500,
    fuel_type: 'Diesel',
    engine_size: 2.3,
    power_hp: 140,
    transmission: 'Manual',
    condition: 'Used',
    city: 'Munich',
    description: 'Compact semi-integrated motorhome, perfect for couples',
    images: '/images/caravans/dethleffs-globebus.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 3,
    brand: 'Knaus',
    model: 'Boxdrive 600 MQ',
    year: 2024,
    price: 58900,
    type: 'Camper Van',
    subtype: 'Van Conversion',
    length: 5.41,
    width: 2.05,
    height: 2.53,
    weight_empty: 2650,
    weight_total: 3000,
    sleeping_capacity: 2,
    num_beds: 1,
    num_axles: 2,
    mileage: 2000,
    fuel_type: 'Diesel',
    engine_size: 2.0,
    power_hp: 163,
    transmission: 'Automatic',
    condition: 'New',
    city: 'Hamburg',
    description: 'Modern camper van on Mercedes Sprinter chassis',
    images: '/images/caravans/knaus-boxdrive.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 1,
    brand: 'Weinsberg',
    model: 'CaraOne 500 QDK',
    year: 2023,
    price: 24900,
    type: 'Travel Trailer',
    subtype: 'Caravan',
    length: 6.29,
    width: 2.3,
    height: 2.59,
    weight_empty: 1200,
    weight_total: 1500,
    sleeping_capacity: 4,
    num_beds: 2,
    num_axles: 1,
    condition: 'Used',
    city: 'Cologne',
    description: 'Family-friendly caravan with queen-size bed',
    images: '/images/caravans/weinsberg-caraone.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 2,
    brand: 'Bürstner',
    model: 'Lyseo Time TD 734 G',
    year: 2023,
    price: 92000,
    type: 'Motorhome',
    subtype: 'Semi-Integrated',
    length: 7.34,
    width: 2.33,
    height: 2.94,
    weight_empty: 3350,
    weight_total: 3850,
    sleeping_capacity: 4,
    num_beds: 3,
    num_axles: 2,
    mileage: 12000,
    fuel_type: 'Diesel',
    engine_size: 2.3,
    power_hp: 160,
    transmission: 'Automatic',
    condition: 'Used',
    city: 'Frankfurt',
    description: 'Spacious family motorhome with garage',
    images: '/images/caravans/buerstner-lyseo.jpg',
    heating: 1,
    ac: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 3,
    brand: 'Adria',
    model: 'Alpina 623 UL Colorado',
    year: 2024,
    price: 28500,
    type: 'Travel Trailer',
    subtype: 'Caravan',
    length: 7.23,
    width: 2.3,
    height: 2.65,
    weight_empty: 1380,
    weight_total: 1700,
    sleeping_capacity: 4,
    num_beds: 2,
    num_axles: 1,
    condition: 'New',
    city: 'Berlin',
    description: 'Modern lightweight caravan with full equipment',
    images: '/images/caravans/adria-alpina.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 1,
    brand: 'Hobby',
    model: 'Optima De Luxe T70 E',
    year: 2023,
    price: 30200,
    type: 'Travel Trailer',
    subtype: 'Caravan',
    length: 7.74,
    width: 2.3,
    height: 2.62,
    weight_empty: 1450,
    weight_total: 1800,
    sleeping_capacity: 5,
    num_beds: 3,
    num_axles: 1,
    condition: 'Used',
    city: 'Nuremberg',
    description: 'Extra-long family caravan with bunk beds',
    images: '/images/caravans/hobby-optima.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 2,
    brand: 'Pilote',
    model: 'Galaxy G740C',
    year: 2024,
    price: 79900,
    type: 'Motorhome',
    subtype: 'Alcove',
    length: 7.39,
    width: 2.33,
    height: 3.18,
    weight_empty: 3200,
    weight_total: 3650,
    sleeping_capacity: 6,
    num_beds: 4,
    num_axles: 2,
    mileage: 5000,
    fuel_type: 'Diesel',
    engine_size: 2.3,
    power_hp: 140,
    transmission: 'Manual',
    condition: 'New',
    city: 'Freiburg',
    description: 'Large family motorhome with alcove bed',
    images: '/images/caravans/pilote-galaxy.jpg',
    heating: 1,
    ac: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 3,
    brand: 'LMC',
    model: 'Vivo 520 E',
    year: 2023,
    price: 21900,
    type: 'Travel Trailer',
    subtype: 'Caravan',
    length: 6.15,
    width: 2.3,
    height: 2.57,
    weight_empty: 1150,
    weight_total: 1400,
    sleeping_capacity: 3,
    num_beds: 2,
    num_axles: 1,
    condition: 'Used',
    city: 'Leipzig',
    description: 'Compact and affordable caravan for beginners',
    images: '/images/caravans/lmc-vivo.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  },
  {
    user_id: 1,
    brand: 'Challenger',
    model: 'Graphite 260 Compact',
    year: 2024,
    price: 64900,
    type: 'Camper Van',
    subtype: 'Van Conversion',
    length: 5.41,
    width: 2.05,
    height: 2.52,
    weight_empty: 2700,
    weight_total: 3100,
    sleeping_capacity: 2,
    num_beds: 1,
    num_axles: 2,
    mileage: 1500,
    fuel_type: 'Diesel',
    engine_size: 2.3,
    power_hp: 140,
    transmission: 'Manual',
    condition: 'New',
    city: 'Hannover',
    description: 'Premium compact camper van with stylish design',
    images: '/images/caravans/challenger-graphite.jpg',
    heating: 1,
    toilet: 1,
    shower: 1,
    kitchen: 1
  }
];

db.serialize(() => {
  const stmt = db.prepare(`
    INSERT INTO ebikes (
      user_id, brand, model, year, price, type, motor_type, motor_power,
      battery_capacity, range_min, range_max, frame_material, suspension, brakes,
      gear_system, tire_size, weight, condition, mileage, city,
      description, images, gears, max_speed
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  ebikes.forEach(ebike => {
    stmt.run(
      ebike.user_id,
      ebike.brand,
      ebike.model,
      ebike.year,
      ebike.price,
      ebike.type,
      ebike.motor_type,
      ebike.motor_power,
      ebike.battery_capacity,
      ebike.range_min,
      ebike.range_max,
      ebike.frame_material,
      ebike.suspension || null,
      ebike.brakes,
      ebike.gear_system,
      ebike.tire_size,
      ebike.weight,
      ebike.condition,
      ebike.mileage || null,
      ebike.city,
      ebike.description,
      ebike.images,
      ebike.gears || null,
      ebike.max_speed || null
    );
  });

  stmt.finalize();

  const caravanStmt = db.prepare(`
    INSERT INTO caravans (
      user_id, brand, model, year, price, type, length, width,
      height, weight_empty, weight_total, sleeping_capacity, beds, axles,
      mileage, engine_type, engine_size, power_hp, transmission, condition,
      city, description, images, heating, air_conditioning, toilet, shower, kitchen
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  caravans.forEach(caravan => {
    caravanStmt.run(
      caravan.user_id,
      caravan.brand,
      caravan.model,
      caravan.year,
      caravan.price,
      caravan.type,
      caravan.length,
      caravan.width,
      caravan.height,
      caravan.weight_empty,
      caravan.weight_total,
      caravan.sleeping_capacity,
      caravan.num_beds,
      caravan.num_axles,
      caravan.mileage || null,
      caravan.fuel_type || null,
      caravan.engine_size || null,
      caravan.power_hp || null,
      caravan.transmission || null,
      caravan.condition,
      caravan.city,
      caravan.description,
      caravan.images,
      caravan.heating || 0,
      caravan.ac || 0,
      caravan.toilet || 0,
      caravan.shower || 0,
      caravan.kitchen || 0
    );
  });

  caravanStmt.finalize();

  console.log('✅ Successfully added 10 e-bikes and 10 caravans!');
  db.close();
});
